source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MusicBarAnimator_Example', :exclusive => true do
  pod 'MusicBarAnimator', :path => '../'
end

target 'MusicBarAnimator_Tests', :exclusive => true do
  pod 'MusicBarAnimator', :path => '../'

  
end
